services:
  mongodb:
    image: mongo:7.0.28-jammy
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_ROOT_USERNAME=root
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:4.2.3-management
    environment:
      - RABBITMQ_DEFAULT_PASS=secret
      - RABBITMQ_DEFAULT_USER=myuser
    ports:
      - 5672:5672
      - 15672:15672

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.10
    environment:
      - ELASTIC_PASSWORD=secret
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200
      - 9300

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.10
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - XPACK_SECURITY_ENABLED=false
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  minio:
    image: quay.io/minio/minio:latest
    ports:
      - 9000:9000 # API Port
      - 9001:9001 # Console UI Port
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server --console-address ":9001" /data
    volumes:
      - minio_data:/data

volumes:
  minio_data: